# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/xiaopei/homworks/CP

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/xiaopei/homworks/CP

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xiaopei/homworks/CP/CMakeFiles /home/xiaopei/homworks/CP/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/xiaopei/homworks/CP/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named lexical

# Build rule for target.
lexical: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 lexical
.PHONY : lexical

# fast build rule for target.
lexical/fast:
	$(MAKE) -f CMakeFiles/lexical.dir/build.make CMakeFiles/lexical.dir/build
.PHONY : lexical/fast

Lexical.o: Lexical.cpp.o

.PHONY : Lexical.o

# target to build an object file
Lexical.cpp.o:
	$(MAKE) -f CMakeFiles/lexical.dir/build.make CMakeFiles/lexical.dir/Lexical.cpp.o
.PHONY : Lexical.cpp.o

Lexical.i: Lexical.cpp.i

.PHONY : Lexical.i

# target to preprocess a source file
Lexical.cpp.i:
	$(MAKE) -f CMakeFiles/lexical.dir/build.make CMakeFiles/lexical.dir/Lexical.cpp.i
.PHONY : Lexical.cpp.i

Lexical.s: Lexical.cpp.s

.PHONY : Lexical.s

# target to generate assembly for a file
Lexical.cpp.s:
	$(MAKE) -f CMakeFiles/lexical.dir/build.make CMakeFiles/lexical.dir/Lexical.cpp.s
.PHONY : Lexical.cpp.s

LexicalTestDrive.o: LexicalTestDrive.cpp.o

.PHONY : LexicalTestDrive.o

# target to build an object file
LexicalTestDrive.cpp.o:
	$(MAKE) -f CMakeFiles/lexical.dir/build.make CMakeFiles/lexical.dir/LexicalTestDrive.cpp.o
.PHONY : LexicalTestDrive.cpp.o

LexicalTestDrive.i: LexicalTestDrive.cpp.i

.PHONY : LexicalTestDrive.i

# target to preprocess a source file
LexicalTestDrive.cpp.i:
	$(MAKE) -f CMakeFiles/lexical.dir/build.make CMakeFiles/lexical.dir/LexicalTestDrive.cpp.i
.PHONY : LexicalTestDrive.cpp.i

LexicalTestDrive.s: LexicalTestDrive.cpp.s

.PHONY : LexicalTestDrive.s

# target to generate assembly for a file
LexicalTestDrive.cpp.s:
	$(MAKE) -f CMakeFiles/lexical.dir/build.make CMakeFiles/lexical.dir/LexicalTestDrive.cpp.s
.PHONY : LexicalTestDrive.cpp.s

StateMachine.o: StateMachine.cpp.o

.PHONY : StateMachine.o

# target to build an object file
StateMachine.cpp.o:
	$(MAKE) -f CMakeFiles/lexical.dir/build.make CMakeFiles/lexical.dir/StateMachine.cpp.o
.PHONY : StateMachine.cpp.o

StateMachine.i: StateMachine.cpp.i

.PHONY : StateMachine.i

# target to preprocess a source file
StateMachine.cpp.i:
	$(MAKE) -f CMakeFiles/lexical.dir/build.make CMakeFiles/lexical.dir/StateMachine.cpp.i
.PHONY : StateMachine.cpp.i

StateMachine.s: StateMachine.cpp.s

.PHONY : StateMachine.s

# target to generate assembly for a file
StateMachine.cpp.s:
	$(MAKE) -f CMakeFiles/lexical.dir/build.make CMakeFiles/lexical.dir/StateMachine.cpp.s
.PHONY : StateMachine.cpp.s

States.o: States.cpp.o

.PHONY : States.o

# target to build an object file
States.cpp.o:
	$(MAKE) -f CMakeFiles/lexical.dir/build.make CMakeFiles/lexical.dir/States.cpp.o
.PHONY : States.cpp.o

States.i: States.cpp.i

.PHONY : States.i

# target to preprocess a source file
States.cpp.i:
	$(MAKE) -f CMakeFiles/lexical.dir/build.make CMakeFiles/lexical.dir/States.cpp.i
.PHONY : States.cpp.i

States.s: States.cpp.s

.PHONY : States.s

# target to generate assembly for a file
States.cpp.s:
	$(MAKE) -f CMakeFiles/lexical.dir/build.make CMakeFiles/lexical.dir/States.cpp.s
.PHONY : States.cpp.s

Token.o: Token.cpp.o

.PHONY : Token.o

# target to build an object file
Token.cpp.o:
	$(MAKE) -f CMakeFiles/lexical.dir/build.make CMakeFiles/lexical.dir/Token.cpp.o
.PHONY : Token.cpp.o

Token.i: Token.cpp.i

.PHONY : Token.i

# target to preprocess a source file
Token.cpp.i:
	$(MAKE) -f CMakeFiles/lexical.dir/build.make CMakeFiles/lexical.dir/Token.cpp.i
.PHONY : Token.cpp.i

Token.s: Token.cpp.s

.PHONY : Token.s

# target to generate assembly for a file
Token.cpp.s:
	$(MAKE) -f CMakeFiles/lexical.dir/build.make CMakeFiles/lexical.dir/Token.cpp.s
.PHONY : Token.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... lexical"
	@echo "... edit_cache"
	@echo "... Lexical.o"
	@echo "... Lexical.i"
	@echo "... Lexical.s"
	@echo "... LexicalTestDrive.o"
	@echo "... LexicalTestDrive.i"
	@echo "... LexicalTestDrive.s"
	@echo "... StateMachine.o"
	@echo "... StateMachine.i"
	@echo "... StateMachine.s"
	@echo "... States.o"
	@echo "... States.i"
	@echo "... States.s"
	@echo "... Token.o"
	@echo "... Token.i"
	@echo "... Token.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

